import type { Book } from '@/lib/types';

export const mockBooks: Book[] = [
  {
    id: 'book-1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverUrl: 'https://picsum.photos/seed/book1/300/400',
    description: 'A novel about the American dream, set in the Roaring Twenties.',
    category: 'Classic Literature',
  },
  {
    id: 'book-2',
    title: 'Dune',
    author: 'Frank Herbert',
    coverUrl: 'https://picsum.photos/seed/book2/300/400',
    description: 'A science fiction epic about politics, religion, and power on a desert planet.',
    category: 'Science Fiction',
  },
  {
    id: 'book-3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    coverUrl: 'https://picsum.photos/seed/book3/300/400',
    description: 'A novel about the serious issues of rape and racial inequality.',
    category: 'Classic Literature',
  },
  {
    id: 'book-4',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    coverUrl: 'https://picsum.photos/seed/book4/300/400',
    description: 'A book that explores the history of humankind from the Stone Age to the present day.',
    category: 'Non-Fiction',
  },
  {
    id: 'book-5',
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    coverUrl: 'https://picsum.photos/seed/book5/300/400',
    description: 'A comedy science fiction series created by Douglas Adams.',
    category: 'Science Fiction',
  },
  {
    id: 'book-6',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    coverUrl: 'https://picsum.photos/seed/book6/300/400',
    description: 'A popular-science book on cosmology by British physicist Stephen Hawking.',
    category: 'Science',
  },
  {
    id: 'book-7',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    coverUrl: 'https://picsum.photos/seed/book7/300/400',
    description: 'A novel about teenage angst and alienation.',
    category: 'Classic Literature',
  },
  {
    id: 'book-8',
    title: 'Cosmos',
    author: 'Carl Sagan',
    coverUrl: 'https://picsum.photos/seed/book8/300/400',
    description: 'A book about the universe and our place in it.',
    category: 'Science',
  },
  {
    id: 'book-9',
    title: '1984',
    author: 'George Orwell',
    coverUrl: 'https://picsum.photos/seed/book9/300/400',
    description: 'A dystopian novel set in a totalitarian society.',
    category: 'Dystopian Fiction',
  },
  {
    id: 'book-10',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    coverUrl: 'https://picsum.photos/seed/book10/300/400',
    description: 'A dystopian novel which explores themes of technology, society, and individuality.',
    category: 'Dystopian Fiction',
  }
];
