import { jsPDF } from "jspdf";
import type { Student, Parent, Class, Remark, SubjectScore } from "@/lib/types";

function gradeFromScore(score: number): string {
  if (score >= 90) return "A+";
  if (score >= 80) return "A";
  if (score >= 70) return "B";
  if (score >= 60) return "C";
  if (score >= 50) return "D";
  return "E";
}

function performanceFromScore(score: number): string {
  if (score >= 90) return "Outstanding";
  if (score >= 80) return "Excellent";
  if (score >= 70) return "Good";
  if (score >= 60) return "Average";
  if (score >= 50) return "Needs Improvement";
  return "Poor";
}

export function generateStudentReportCard(opts: {
  student: Student;
  parent?: Parent;
  studentClass?: Class;
}): void {
  const { student, parent, studentClass } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 40;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("AtendaLearn - Report Card", pageWidth / 2, y, { align: "center" });
  y += 24;
  doc.setDrawColor(120);
  doc.line(40, y, pageWidth - 40, y);
  y += 20;

  // Student Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  const rollNo = student.id; // Using student id as roll number
  const gradeLetter = gradeFromScore(student.averageScore);
  const performance = performanceFromScore(student.averageScore);
  const className = studentClass?.name ?? "N/A";
  const parentName = parent?.name ?? "N/A";

  doc.text(`Name: ${student.name}`, 40, y); y += 18;
  doc.text(`Roll No: ${rollNo}`, 40, y); y += 18;
  doc.text(`Class: ${className}`, 40, y); y += 18;
  doc.text(`Parent: ${parentName}`, 40, y); y += 18;
  doc.text(`Attendance: ${student.attendancePercentage}%`, 40, y); y += 18;
  doc.text(`Performance: ${performance}`, 40, y); y += 18;
  doc.text(`Grade: ${gradeLetter}`, 40, y); y += 26;

  // Subject-wise Marks
  doc.setFont("helvetica", "bold");
  doc.text("Subject-wise Marks", 40, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  const scores: SubjectScore[] = student.scores ?? [];
  if (scores.length === 0) {
    doc.text("No subject scores available.", 40, y);
    y += 18;
  } else {
    // Table-like layout
    doc.setFontSize(11);
    doc.text("Subject", 40, y);
    doc.text("Marks", pageWidth - 120, y);
    y += 12;
    doc.setDrawColor(200); doc.line(40, y, pageWidth - 40, y); y += 10;
    scores.forEach(s => {
      doc.text(s.subject, 40, y);
      doc.text(String(s.score), pageWidth - 120, y);
      y += 16;
    });
    y += 10;
  }

  // Teacher Remarks
  doc.setFont("helvetica", "bold");
  doc.text("Teacher Remarks", 40, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  const remarks: Remark[] = student.remarks ?? [];
  if (remarks.length === 0) {
    doc.text("No remarks available.", 40, y);
    y += 18;
  } else {
    const maxRemarks = 6;
    remarks.slice(0, maxRemarks).forEach(r => {
      const line = `- ${r.content}  (${r.teacherName})`;
      const lines = doc.splitTextToSize(line, pageWidth - 80);
      doc.text(lines, 40, y);
      y += 16 + (lines.length - 1) * 14;
    });
  }

  // Footer
  y = Math.min(y + 10, doc.internal.pageSize.getHeight() - 40);
  doc.setDrawColor(120);
  doc.line(40, y, pageWidth - 40, y);
  y += 18;
  doc.setFontSize(10);
  doc.text("Generated by AtendaLearn", pageWidth / 2, y, { align: "center" });

  // Save
  const filename = `ReportCard_${student.name.replace(/\s+/g, "_")}_${rollNo}.pdf`;
  doc.save(filename);
}
